### PR TITLE
Adds MacOS support

### PR DESCRIPTION
**Pull request by leshniak**
The setup is pretty similar to the one for Linux.

Zrzut ekranu 2023-08-3 o 23 46 02

73,
SP3ML

### CODE REVIEW

**Comment by leshniak** [comment]
Hm, I'm experiencing weird freezes after transmiting :/

Zrzut ekranu 2023-08-4 o 12 30 05

**Comment by leshniak** [comment]
So far I've found that pushing every 4th bunch of samples (by doing `if status[0] and i % 4 == 0: ser.write(samples8)` in `transmit_audio_via_serial()`) keeps CAT stable.

Any suggestions?

**Comment by leshniak** [comment]
After many hours of investigation I've figured out, that the system drivers for CH340 are broken... Need to install https://github.com/WCHSoftGroup/ch34xser_macos

**Comment by leshniak** [comment]
With the new driver, I've managed to make it work, but basing on Olgierd's script for now.

Zrzut ekranu 2023-08-6 o 22 10 18

**Comment by nolith** [comment]
@leshniak do you mind expanding a bit on how you fixed it?

I have the exact same issue.

Should I just install https://github.com/WCHSoftGroup/ch34xser_macos or did you also tweaked the python script?

Thank you

**Pull request merged**
